--- 
title: "1-Way ANOVA- Model Representations, Power, and Sample Size Tutorial"
author: "Simon Marks"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a interactive 1-way ANOVA tutorial built with bookdown."
---

# Introduction {#intro}

ANOVA is short for analysis of variance. It is a widely used statistical method used with designed experiments. Given its frequency of use, it is my opinion that anyone interested in academic research understand the basics. . . even if you never use it in your own research, I guarantee you will encounter it somewhere in the literature! Briefly, ANOVA is an "accounting" procedure that keeps track of all the variation in a response variable. ANOVA partitions this variation into pieces and uses these pieces to assess the likelihood that differences found between means in sample data could be the result of random chance.

This tutorial focuses on 1-way ANOVA, specifically ways to model our data in the context of this statistical method. We introduce the means and effects models and their assumptions and implement these approaches manually in R. We also discuss power and sample size and provide an interactive visualization to see what influences power in an ANOVA. Discussion of power and sample size helps answer the question: "How might we increase the chances of getting a statistically significant result from our ANOVA?" Thinking about power and sample size not only will bolster your statistical chops, it might also come in handy in practice when planning research design or writing research grant proposals.

The tutorial assumes you have used R before and are familar working with matrices. Some examples and demos utilize functions from the **Tidyverse** [@R-tidyverse]. This tutorial was written using the **bookdown** package [@R-bookdown], which was built on top of R Markdown and **knitr** [@xie2015].

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'tidyverse'
), 'packages.bib')
```
