<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Part 2 ANOVA Basics | 1-Way ANOVA- Model Representations, Power, and Sample Size Tutorial</title>
  <meta name="description" content="This is a 1-way ANOVA tutorial built with bookdown." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Part 2 ANOVA Basics | 1-Way ANOVA- Model Representations, Power, and Sample Size Tutorial" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a 1-way ANOVA tutorial built with bookdown." />
  <meta name="github-repo" content="sjmarks/anovatutorial" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Part 2 ANOVA Basics | 1-Way ANOVA- Model Representations, Power, and Sample Size Tutorial" />
  
  <meta name="twitter:description" content="This is a 1-way ANOVA tutorial built with bookdown." />
  

<meta name="author" content="Simon Marks" />


<meta name="date" content="2020-06-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="meanseffects.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">1-Way ANOVA Tutorial</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> ANOVA Basics</a><ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#check-in"><i class="fa fa-check"></i><b>2.1</b> Check-in</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="meanseffects.html"><a href="meanseffects.html"><i class="fa fa-check"></i><b>3</b> The Means and Effects Models</a><ul>
<li class="chapter" data-level="3.1" data-path="meanseffects.html"><a href="meanseffects.html#bookkeep"><i class="fa fa-check"></i><b>3.1</b> ANOVA Bookkeeping</a></li>
<li class="chapter" data-level="3.2" data-path="meanseffects.html"><a href="meanseffects.html#means-model"><i class="fa fa-check"></i><b>3.2</b> Means Model</a><ul>
<li class="chapter" data-level="3.2.1" data-path="meanseffects.html"><a href="meanseffects.html#employing-the-means-model-to-do-1-way-anova-in-r"><i class="fa fa-check"></i><b>3.2.1</b> Employing the Means Model to do 1-way ANOVA in R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="meanseffects.html"><a href="meanseffects.html#effects-model"><i class="fa fa-check"></i><b>3.3</b> Effects Model</a><ul>
<li class="chapter" data-level="3.3.1" data-path="meanseffects.html"><a href="meanseffects.html#employing-the-effects-model-to-do-1-way-anova-in-r"><i class="fa fa-check"></i><b>3.3.1</b> Employing the Effects Model to do 1-way ANOVA in R</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="meanseffects.html"><a href="meanseffects.html#check-in-1"><i class="fa fa-check"></i><b>3.4</b> Check-in</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>4</b> Power and Sample Size</a><ul>
<li class="chapter" data-level="4.1" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#power"><i class="fa fa-check"></i><b>4.1</b> Power</a></li>
<li class="chapter" data-level="4.2" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#playing-with-sample-size"><i class="fa fa-check"></i><b>4.2</b> Playing with Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="check-in-answers.html"><a href="check-in-answers.html"><i class="fa fa-check"></i><b>5</b> Check-in Answers</a><ul>
<li class="chapter" data-level="5.1" data-path="check-in-answers.html"><a href="check-in-answers.html#part-2"><i class="fa fa-check"></i><b>5.1</b> Part 2</a></li>
<li class="chapter" data-level="5.2" data-path="check-in-answers.html"><a href="check-in-answers.html#part-3"><i class="fa fa-check"></i><b>5.2</b> Part 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">1-Way ANOVA- Model Representations, Power, and Sample Size Tutorial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basics" class="section level1">
<h1><span class="header-section-number">Part 2</span> ANOVA Basics</h1>
<p>As alluded to in Part <a href="index.html#intro">1</a> of this tutorial, we use ANOVA to make decisions about the relationships among means. Typically we do this when we have <strong>more than two</strong> treatment groups. This is because we could simply use a two-sample t-test to compare two (independent) groups. The power of ANOVA is that we can compare more than two means. For example, let us look at the <code>InsectSprays</code> data set in R <span class="citation">(Beall <a href="#ref-beall1942" role="doc-biblioref">1942</a>)</span>. This simple data set provides counts of insects treated with 6 different insecticides.</p>
<p>First, let us consider the components of this experiment and its design:</p>
<p><strong>Treatment Structure</strong></p>
<ul>
<li><p>Factor: Insecticide (spray)</p></li>
<li><p>Level: 6 levels (A, B, C, D, E, F)</p></li>
</ul>
<p><strong>Design Structure</strong></p>
<ul>
<li><p>Experimental Unit: A plot of insects</p></li>
<li><p>Randomization Method: Completely randomized design (CRD)</p></li>
<li><p>Replication: 12 replicates per type of insecticide (spray)</p></li>
</ul>
<p><strong>Response Variable</strong></p>
<ul>
<li>Number of insects counted in a plot after application of insecticide</li>
</ul>
<p>The design structure above warrants some additional discussion. Firstly, the experimental unit is defined as the unit that the treatment is applied. The randomization method of CRD communicates that the experimental units were randomly assigned to each treatment. In this case, insect plots were randomly assigned one of the 6 sprays. Random assignment <em><strong>equalizes</strong></em> the extraneous sources of variability in comparison of the treatment groups. This enables cause and effect conclusions to be drawn from the experiment, protecting against extra variation in the response variable from becoming confounding variables. For example, we might assume that the insects in this study have genetic variation which would make some insects more or less susceptible to certain sprays- CRD makes sure this isn’t the reason a plot responds a certain way to one of the 6 sprays. Lastly, replication is important because it serves to distribute extraneous variation in the response equally, giving us a reasonably equal variance within all treatment groups.</p>
<p>With the preliminaries out of the way, let us now explore the <code>InsectSprays</code> data:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1">insects &lt;-<span class="st"> </span>InsectSprays </a>
<a class="sourceLine" id="cb1-2" title="2"></a>
<a class="sourceLine" id="cb1-3" title="3">insects <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1-4" title="4"><span class="st">  </span><span class="kw">group_by</span>(spray) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb1-5" title="5"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(count), <span class="st">`</span><span class="dt">std dev</span><span class="st">`</span> =<span class="st"> </span><span class="kw">sd</span>(count))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   spray  mean `std dev`
##   &lt;fct&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 A     14.5       4.72
## 2 B     15.3       4.27
## 3 C      2.08      1.98
## 4 D      4.92      2.50
## 5 E      3.5       1.73
## 6 F     16.7       6.21</code></pre>
<div class="figure" style="text-align: left"><span id="fig:insect-boxplot"></span>
<img src="anova-tutorial_files/figure-html/insect-boxplot-1.png" alt="Boxplot showing differences and variation in count response between insecticide treatment groups." width="80%" />
<p class="caption">
Figure 2.1: Boxplot showing differences and variation in count response between insecticide treatment groups.
</p>
</div>
<p>Looking at the produced tibble and box plot, it appears that there is variability in insect count for insect plots exposed to different insecticides. Insect plots exposed to <strong>Spray F</strong> had the highest count on average (16.7), while insect plots exposed to <strong>Spray C</strong> had the lowest count on average (2.08). The graph and table also illustrate differences in within treatment group variation for the 6 sprays; the spread of the observations vary between each group. For example, the <strong>Spray E</strong> group had low variance with a standard deviation of 1.73 insects, while <strong>Spray F</strong> had high variance with a standard deviation of 6.21 insects.</p>
<p>These initial observations from our data exploration are nice, but the question remains as to whether or not the observed variation in the insect counts is truly due to variation due to spray. The next part of the tutorial will demonstrate two models for our data that will help us answer this question.</p>
<div id="check-in" class="section level2">
<h2><span class="header-section-number">2.1</span> Check-in</h2>
<ol style="list-style-type: decimal">
<li><p>Suppose the insect plots in the above experiment were comprised using only one insect species. What is one <em>statistical advantage</em> of doing this?</p></li>
<li><p>What is the <em>statistical disadvantage</em> of limiting plots to one type of insect species?</p></li>
</ol>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-beall1942">
<p>Beall, Geoffrey. 1942. “The Transformation of Data from Entomological Field Experiments so That the Analysis of Variance Becomes Applicable.” <em>Biometrika</em> 32 (3/4): 243–62.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="meanseffects.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["anova-tutorial.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
